name: "CI/CD Pipeline for LMS Back-End"

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checking out the repo
        uses: actions/checkout@v3

      - name: Create artifact for application
        run: mvn compile package

      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.SERVICE_ACCOUNT_PRIVATE_KEY }}'

      - name: 'Setting up gcloud'
        uses: 'google-github-actions/setup-gcloud@v0'

      - name: Deploying artifact
        run: gcloud compute scp --zone="asia-south2-a" target/lms-back-end-1.0.0.war dep-vm:~

